#!/bin/bash
set -eu

# Ensure correct local path.
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR

mkdir -p /srv/www
cd /srv/www

if [ -d "SwarmUI" ]; then
    mv SwarmUI SwarmUI_bak
fi

# Download swarm
git clone https://github.com/mcmonkeyprojects/SwarmUI --depth 1 --branch 0.9.3-Beta

echo "Restoring SwarmUI data from a backup. This may take some time. Please wait..."
if [ -d "SwarmUI_bak" ]; then
    # Move models instead of copy since they take up a lot of space
    if [ -d "SwarmUI_bak/Models" ]; then
        rm -rf SwarmUI/Models 2>/dev/null ||:
        mv SwarmUI_bak/Models SwarmUI/
    fi
    # Next, move the Output folder since it may contain a lot of data
    if [ -d "SwarmUI_bak/Output" ]; then
        rm -r SwarmUI/Output 2>/dev/null ||:
        mv SwarmUI_bak/Output SwarmUI/
    fi
    # Copy over the rest
    rsync -avu SwarmUI_bak/ SwarmUI/
    rm -r SwarmUI_bak
fi

cd SwarmUI

# install dotnet
cd launchtools
# https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install
wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
chmod +x dotnet-install.sh

# Note: manual installers that want to avoid home dir, add to both of the below lines: --install-dir $SCRIPT_DIR/.dotnet
./dotnet-install.sh --channel 8.0 --runtime aspnetcore
./dotnet-install.sh --channel 8.0
cd ..

# Build the project
/root/.dotnet/dotnet build src/SwarmUI.csproj --configuration Release -o ./src/bin/live_release

# Install ComfyUI
bash ./launchtools/comfy-install-linux.sh nv

# Copy configuration files
if [ ! -d "Data" ]; then
    rsync -au /usr/share/swarmui/ .
fi

# Download models
MODEL_DIR="/srv/www/SwarmUI/Models/Stable-Diffusion"
IMAGE_GEN_MODELS=("CyberRealistic_V4.2_FP16.safetensors" "dreamshaperXL_v21TurboDPMSDE.safetensors") 
mkdir -p "$MODEL_DIR"
for model in "${IMAGE_GEN_MODELS[@]}"
do
    if [ ! -f "$MODEL_DIR/$model" ]; then
        wget "https://huggingface.co/InsightReactions/TinyLlama/resolve/main/${model}?download=true" -O "$MODEL_DIR/$model"
    fi
done

# Download upscalers
UPSCALE_DIR="/srv/www/SwarmUI/Models/upscale_models"
UPSCALE_MODELS=("4xUltrasharp_4xUltrasharpV10.pt")
mkdir -p "$UPSCALE_DIR"
for upscaler in "${UPSCALE_MODELS[@]}"
do
    if [ ! -f "$UPSCALE_DIR/$upscaler" ]; then
        wget "https://huggingface.co/InsightReactions/TinyLlama/resolve/main/${upscaler}?download=true" -O "$UPSCALE_DIR/${upscaler}"
    fi
done

systemctl enable swarmui
systemctl start swarmui
