#!/bin/bash
set -eu

# Ensure correct local path.
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR

mkdir -p /srv/www
cd /srv/www

if [ -d "SwarmUI" ]; then
    mv SwarmUI SwarmUI_bak
fi

# Download swarm
git clone https://github.com/mcmonkeyprojects/SwarmUI --depth 1 --branch 0.9.0-Beta

if [ -d "SwarmUI_bak" ]; then
    rsync -au SwarmUI_bak/ SwarmUI/
    rm -r SwarmUI_bak
else
    cp "/usr/share/swarmui/Data/Users.ldb" "/srv/www/SwarmUI/Data/Users.ldb"
fi

cd SwarmUI

# install dotnet
cd launchtools
# https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install
wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
chmod +x dotnet-install.sh

# Note: manual installers that want to avoid home dir, add to both of the below lines: --install-dir $SCRIPT_DIR/.dotnet
./dotnet-install.sh --channel 8.0 --runtime aspnetcore
./dotnet-install.sh --channel 8.0
cd ..

# Build the project
/root/.dotnet/dotnet build src/SwarmUI.csproj --configuration Release -o ./src/bin/live_release

# Install ComfyUI
bash ./launchtools/comfy-install-linux.sh

# Copy configuration files
if [ ! -d "Data" ]; then
    mkdir -p Data
    rsync -au /usr/share/swarmui/ .
fi

systemctl enable swarmui
systemctl start swarmui
