#!/bin/bash
set -eu

export OLLAMA_MODELS=/usr/share/ollama/.ollama/models
ollama pull hermes3
ollama pull llama3.1
ollama pull minicpm-v

mkdir -p /srv/www/open-webui
docker pull ghcr.io/open-webui/open-webui:git-506dc01

DEFAULT_IMAGE_GEN_MODEL="CyberRealistic_V4.2_FP16.safetensors"
WEBUI_DIR="/srv/www/open-webui"
if ! grep -q "image_generation" $WEBUI_DIR/config.json; then
    rm $WEBUI_DIR/config.json ||:
fi

if [ ! -f "$WEBUI_DIR/config.json" ]; then
    cat <<EOF > $WEBUI_DIR/config.json
{
    "image_generation": {
		"engine": "comfyui",
		"enable": true,
		"comfyui": {
			"base_url": "http://localhost:7821"
		},
		"model": "${DEFAULT_IMAGE_GEN_MODEL}",
		"size": "512x512",
		"steps": 30
	},
    "ui": {
		"default_models": "llama3.1"
	}
}
EOF
fi

systemctl enable open-webui
systemctl start open-webui
