#!/bin/bash
set -e

cd /srv/www/TinyLlama

# Configure TinyLlama service
python3 -m venv venv
source venv/bin/activate
python3 -m pip install -r ./requirements.txt

# Start TinyLlama Service
systemctl enable tinyllama
systemctl start tinyllama
