#!/bin/bash
set -e

cd /srv/www/tinyllama

# Add tinyllama Service
python3 -m venv venv
source venv/bin/activate
pip install -r ./requirements.txt

systemctl enable tinyllama
systemctl start tinyllama
