#!/bin/bash
set -eu

# If the ollama user or group exists when the install script runs, it will fail
if id ollama &>/dev/null; then
  userdel ollama &>/dev/null ||:
fi
if getent group ollama &>/dev/null; then
  groupdel ollama &>/dev/null ||:
fi

# Ollama
export OLLAMA_VERSION="0.4.1"
curl -fsSL https://ollama.com/install.sh | sh

# Restore backup if it exists
mv /usr/share/.ollama /usr/share/ollama/ &>/dev/null ||:

# Ollama service configuration
OLLAMA_SERVICE="/etc/systemd/system/ollama.service"
OLLAMA_HOST_STR="Environment=\"OLLAMA_HOST=0.0.0.0\""
OLLAMA_NOHISTORY_STR="Environment=\"OLLAMA_NOHISTORY=1\""
OLLAMA_ORIGINS="Environment=\"OLLAMA_ORIGINS=*\""
line=$(grep -n "ExecStart" $OLLAMA_SERVICE | cut -d ":" -f 1)
sed -i "${line}i ${OLLAMA_HOST_STR}" $OLLAMA_SERVICE
sed -i "${line}i ${OLLAMA_NOHISTORY_STR}" $OLLAMA_SERVICE
sed -i "${line}i ${OLLAMA_ORIGINS}" $OLLAMA_SERVICE

systemctl daemon-reload
systemctl enable ollama
systemctl restart ollama
