#!/bin/bash
rm /etc/systemd/system/ollama.service ||:
rm /usr/bin/ollama ||:
groupdel ollama ||:
userdel -r ollama ||:

echo "Ollama user data must be removed manually, if desired, at path /usr/share/ollama"
