#!/bin/bash

function get_default_route_ip {
    # Get the default route IP address
    output=$(ip route)

    while IFS= read -r line; do
        if [[ $line =~ 'default' ]]; then
            words=($line)
            for (( i=0; i<${#words[@]}; i++ )); do
                if [[ ${words[i]} == 'src' ]]; then
                    echo "${words[i+1]}"
                    return
                fi
            done
        fi
    done <<< "$output"
}

set -eu

DEFAULT_ROUTE_IP=$(get_default_route_ip)

export OLLAMA_MODELS=/usr/share/ollama/.ollama/models
ollama pull hermes3
ollama pull minicpm-v

cd /srv/www

rm -rf amica 2>/dev/null ||:

git clone https://github.com/semperai/amica.git --single-branch --branch master
cd amica

git checkout 2015b49
npm install

cp /usr/share/amica/.env.local ./
sed -i "s/<IP_ADDR>/${DEFAULT_ROUTE_IP}/g" .env.local

systemctl enable amica
systemctl start amica
