#!/bin/bash
set -e

ollama pull taozhiyuai/hermes-2-theta-llama-3:8b-q4_k_m
ollama pull llama3:instruct
ollama pull llava-phi3

# Image Generation
MODEL_DIR="/srv/www/StableSwarmUI/Models/Stable-Diffusion"
IMAGE_GEN_MODEL="CyberRealistic_V4.2_FP16.safetensors"
if [ ! -f "$MODEL_DIR/$IMAGE_GEN_MODEL" ]; then
	wget "https://huggingface.co/InsightReactions/TinyLlama/resolve/main/${IMAGE_GEN_MODEL}?download=true" -O "$MODEL_DIR/$IMAGE_GEN_MODEL"
fi

# Open-WebUI Config
WEBUI_DIR="/srv/www/open-webui"
if ! grep -q "image_generation" $WEBUI_DIR/config.json; then
    rm $WEBUI_DIR/config.json ||:
fi

if [ ! -f "$WEBUI_DIR/config.json" ]; then
    cat <<EOF > $WEBUI_DIR/config.json
{
    "image_generation": {
		"engine": "comfyui",
		"enable": true,
		"comfyui": {
			"base_url": "http://localhost:7821"
		},
		"model": "${IMAGE_GEN_MODEL}",
		"size": "1024x1024",
		"steps": 24
	},
    "ui": {
		"default_models": "llama3:instruct"
	}
}
EOF
fi
