#!/bin/bash

cd /srv/www

if [ -d "StableSwarmUI/Models" ] || [ -d "StableSwarmUI/Output" ] || [ -d "StableSwarmUI/Data" ]; then
    mv StableSwarmUI/Models ./Models_bak ||:
    mv StableSwarmUI/Output ./Output_bak ||:
    mv StableSwarmUI/Data ./Data_bak ||:
    rm -r StableSwarmUI ||:
    mkdir StableSwarmUI
    mv ./Models_bak StableSwarmUI/Models ||:
    mv ./Output_bak StableSwarmUI/Output ||:
    mv ./Data_bak StableSwarmUI/Data ||:
fi

echo "StableSwarmUI user data must be removed manually, if desired, at path /srv/www/StableSwarmUI and /root/.dotnet"
